//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPowerTray.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NPowerTray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NPowerTray....
        /// </summary>
        internal static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User.
        /// </summary>
        internal static string ActionChangeUser {
            get {
                return ResourceManager.GetString("ActionChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Hibernate.
        /// </summary>
        internal static string ActionForceHibernate {
            get {
                return ResourceManager.GetString("ActionForceHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Hibernate (disable WakeUp Events).
        /// </summary>
        internal static string ActionForceHibernateDisableWakeupEvents {
            get {
                return ResourceManager.GetString("ActionForceHibernateDisableWakeupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Log Off.
        /// </summary>
        internal static string ActionForceLogOff {
            get {
                return ResourceManager.GetString("ActionForceLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Reboot.
        /// </summary>
        internal static string ActionForceReboot {
            get {
                return ResourceManager.GetString("ActionForceReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Shutdown.
        /// </summary>
        internal static string ActionForceShutdown {
            get {
                return ResourceManager.GetString("ActionForceShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Sleep.
        /// </summary>
        internal static string ActionForceSleep {
            get {
                return ResourceManager.GetString("ActionForceSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Sleep (disable WakeUp Events).
        /// </summary>
        internal static string ActionForceSleepDisableWakeupEvents {
            get {
                return ResourceManager.GetString("ActionForceSleepDisableWakeupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        internal static string ActionHibernate {
            get {
                return ResourceManager.GetString("ActionHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate (disable WakeUp Events).
        /// </summary>
        internal static string ActionHibernateDisableWakeupEvents {
            get {
                return ResourceManager.GetString("ActionHibernateDisableWakeupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid Shutdown.
        /// </summary>
        internal static string ActionHybridShutdown {
            get {
                return ResourceManager.GetString("ActionHybridShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string ActionLock {
            get {
                return ResourceManager.GetString("ActionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string ActionLogOff {
            get {
                return ResourceManager.GetString("ActionLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string ActionReboot {
            get {
                return ResourceManager.GetString("ActionReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string ActionShutdown {
            get {
                return ResourceManager.GetString("ActionShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string ActionSleep {
            get {
                return ResourceManager.GetString("ActionSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep (disable WakeUp Events).
        /// </summary>
        internal static string ActionSleepDisableWakeupEvents {
            get {
                return ResourceManager.GetString("ActionSleepDisableWakeupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelTimer {
            get {
                return ResourceManager.GetString("CancelTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check NOW.
        /// </summary>
        internal static string CheckNow {
            get {
                return ResourceManager.GetString("CheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tray Icon.
        /// </summary>
        internal static string CloseTrayIcon {
            get {
                return ResourceManager.GetString("CloseTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Hibernate.
        /// </summary>
        internal static string ConvertToHibernate {
            get {
                return ResourceManager.GetString("ConvertToHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Reboot.
        /// </summary>
        internal static string ConvertToReboot {
            get {
                return ResourceManager.GetString("ConvertToReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Shutdown.
        /// </summary>
        internal static string ConvertToShutdown {
            get {
                return ResourceManager.GetString("ConvertToShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Sleep.
        /// </summary>
        internal static string ConvertToSleep {
            get {
                return ResourceManager.GetString("ConvertToSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright: © David Quintana.
        /// </summary>
        internal static string CopyrightNotice {
            get {
                return ResourceManager.GetString("CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default action.
        /// </summary>
        internal static string DefaultActionChoice {
            get {
                return ResourceManager.GetString("DefaultActionChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fnil\fcharset0 Georgia;}{\f1\fnil\fcharset2 Symbol;}}
        ///\viewkind4\uc1\pard\sa200\sl276\slmult1\qj\lang10\fs20 Copyright (c) 2012, David Quintana &lt;gigaherz@gmail.com&gt;\line All rights reserved.\par
        ///Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\par
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-360\li720\sa200\sl276\slmult1\qj Redist [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string DisclaimerTitle {
            get {
                return ResourceManager.GetString("DisclaimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours to {1}.
        /// </summary>
        internal static string HoursToAction {
            get {
                return ResourceManager.GetString("HoursToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string HoursToShutdown1 {
            get {
                return ResourceManager.GetString("HoursToShutdown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hours.
        /// </summary>
        internal static string HoursToShutdown12 {
            get {
                return ResourceManager.GetString("HoursToShutdown12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        internal static string HoursToShutdown2 {
            get {
                return ResourceManager.GetString("HoursToShutdown2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 hours.
        /// </summary>
        internal static string HoursToShutdown24 {
            get {
                return ResourceManager.GetString("HoursToShutdown24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 hours.
        /// </summary>
        internal static string HoursToShutdown4 {
            get {
                return ResourceManager.GetString("HoursToShutdown4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 hours.
        /// </summary>
        internal static string HoursToShutdown8 {
            get {
                return ResourceManager.GetString("HoursToShutdown8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Options.
        /// </summary>
        internal static string MenuSpecialOptions {
            get {
                return ResourceManager.GetString("MenuSpecialOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes to {1}.
        /// </summary>
        internal static string MinutesToAction {
            get {
                return ResourceManager.GetString("MinutesToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes.
        /// </summary>
        internal static string MinutesToShutdown10 {
            get {
                return ResourceManager.GetString("MinutesToShutdown10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        internal static string MinutesToShutdown15 {
            get {
                return ResourceManager.GetString("MinutesToShutdown15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string MinutesToShutdown30 {
            get {
                return ResourceManager.GetString("MinutesToShutdown30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 minutes.
        /// </summary>
        internal static string MinutesToShutdown45 {
            get {
                return ResourceManager.GetString("MinutesToShutdown45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes.
        /// </summary>
        internal static string MinutesToShutdown5 {
            get {
                return ResourceManager.GetString("MinutesToShutdown5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version found: {0}.
        ///Do you want to visit the website to download?.
        /// </summary>
        internal static string NewVersionMessage {
            get {
                return ResourceManager.GetString("NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap npower {
            get {
                object obj = ResourceManager.GetObject("npower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap npower16 {
            get {
                object obj = ResourceManager.GetObject("npower16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap npower48 {
            get {
                object obj = ResourceManager.GetObject("npower48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds to {1}.
        /// </summary>
        internal static string SecondsToAction {
            get {
                return ResourceManager.GetString("SecondsToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string ShowAbout {
            get {
                return ResourceManager.GetString("ShowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Info....
        /// </summary>
        internal static string ShowLicense {
            get {
                return ResourceManager.GetString("ShowLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown after.
        /// </summary>
        internal static string ShutdownAfter {
            get {
                return ResourceManager.GetString("ShutdownAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows Desktop.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPowerTray (Double Click to {0}).
        /// </summary>
        internal static string TrayIconTooltip {
            get {
                return ResourceManager.GetString("TrayIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string UpdatesTitle {
            get {
                return ResourceManager.GetString("UpdatesTitle", resourceCulture);
            }
        }
    }
}
